# Use the official Ubuntu image
{% if inp_info.get("os_drdown") != "" %}
FROM {{ inp_info.get("os_drdown") }} as builder
{% else %}
FROM ubuntu:latest as builder
{% endif %}

# Update and upgrade packages
# Install Python and pip
RUN apt-get update -y && \
    apt-get install -o Acquire::http::Pipeline-Depth=0 -y {{ inp_info.get("script_ln", "python3") }} python3-pip && \
    ln -sf /usr/bin/{{ inp_info.get("script_ln", "python3") }} /usr/bin/python3

# Use the official Ubuntu image
{% if inp_info.get("os_drdown") != "" %}
FROM {{ inp_info.get("os_drdown") }}
{% else %}
FROM ubuntu:latest
{% endif %}

# Copy only the installed Python and Pip binaries from the builder stage
#COPY --from=builder /usr/bin/{{ inp_info.get("script_ln", "python3") }} /usr/bin/{{ inp_info.get("script_ln", "python3") }}
#COPY --from=builder /usr/lib /usr/lib
#COPY --from=builder /etc/ssl /etc/ssl
#COPY --from=builder /usr/bin/python3 /usr/bin/python3
#COPY --from=builder /usr/bin/pip3 /usr/bin/pip3
COPY --from=builder / /

# Create and set the working directory
WORKDIR /{{ session_name }}

# Set the entrypoint to run hello_world.py
CMD ["/bin/bash", "runScript.sh"]

